import java.time.Duration

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'com.github.spotbugs' version '6.0.1'
    id 'com.avast.gradle.docker-compose' version '0.16.13'
    id 'org.openapi.generator' version '7.3.0'
}

group = 'com.camlong'
version = '0.0.1-SNAPSHOT'
description = 'Backend service for hom nay an gi'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-flyway-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

dockerCompose {
    useComposeFiles = [file('cd/docker/docker-compose-local.yml')] as Iterable<? extends String>
    removeOrphans = true
    waitForHealthyStateTimeout = Duration.ofMinutes(1)
}

tasks.register('startTestEnvironment') {
    dependsOn 'composeUp'
}

tasks.register('stopTestEnvironment') {
    dependsOn 'composeDown'
}

tasks.register('startApp') {
    dependsOn tasks.named('startTestEnvironment')
}

spotbugs {
    toolVersion = '4.8.3'
    ignoreFailures = false
    showStackTraces = true
    excludeFilter = file('config/spotbugs/excludeFilter.xml')
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/openapi.yaml"
    outputDir = "$buildDir/generated"
    apiPackage = "com.camlong.homnayangi.inbound.apis"
    modelPackage = "com.camlong.homnayangi.inbound.models"
//    invokerPackage = "com.camlong.invoker"

    configOptions = [
            interfaceOnly      : "true",
            useSpringBoot3     : "true",
            dateLibrary        : "java8",
            useTags            : "true",
            openApiNullable    : "false",
            serializationLibrary: "jackson"
    ]
}
