spring:
  datasource:
    host: 192.168.1.12
    port: 5432
    dbname: homnayangi_db
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/liquibase-changelog-test.xml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: true
  security:
    user:
      name: admin
      password: admin
